select
    pkid as period_info_id,
    assignment_id,
    period_id,
    activity_period_id,
    consolidation_id,
    financial_statement_id,
    active_status as is_active,
    activity_in_period as has_activity,
    key_account as is_key_account,
    is_elimination_account,
    balance_gl,
    balance_gl_base,
    balance_gl_func,
    balance_bank,
    balance_bank_base,
    balance_bank_func,
    balance_subledger,
    balance_subledger_base,
    balance_subledger_func,
    balance_estimate,
    balance_estimate_base,
    balance_estimate_func,
    balance_forecast,
    balance_forecast_base,
    balance_forecast_func,
    purpose,
    reconciliation_procedure,
    recon_frequency,
    custom_frequency,
    child_count,
    parent_id,
    variance_activity_period_id,
    variance_creation_id,
    variance_period_id,
    last_update_date,
    account_balance_last_update_date,
    delete_flag as is_deleted,
    db_insert_date as created_at,
    db_update_date as updated_at
from {{ source('replica', 'rec_period_information') }}
where delete_flag = false or delete_flag is null
