-- ============================================================
-- 05_grants.sql
-- Grants permissions for demo users to access all objects
-- 
-- Adjust role as needed (PUBLIC grants to all users)
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- Database and schema access
GRANT USAGE ON DATABASE WORKSHOP_DB TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA WORKSHOP_DB.DEMO TO ROLE PUBLIC;

-- Warehouse access (required for agent to execute queries)
GRANT USAGE ON WAREHOUSE WORKSHOP_WH TO ROLE PUBLIC;

-- Table access
GRANT SELECT ON TABLE WORKSHOP_DB.DEMO.BILLING_DATA TO ROLE PUBLIC;
GRANT SELECT ON TABLE WORKSHOP_DB.DEMO.COST_RECOMMENDATIONS TO ROLE PUBLIC;
GRANT SELECT ON TABLE WORKSHOP_DB.DEMO.FORECAST_LOG TO ROLE PUBLIC;
GRANT SELECT ON TABLE WORKSHOP_DB.DEMO.FORECAST_BASELINE TO ROLE PUBLIC;

-- Cortex Search Service access
GRANT USAGE ON CORTEX SEARCH SERVICE WORKSHOP_DB.DEMO.TEXT_SEARCH TO ROLE PUBLIC;

-- Semantic View access
GRANT SELECT, REFERENCES ON SEMANTIC VIEW WORKSHOP_DB.DEMO.COST_SEMANTIC_VIEW TO ROLE PUBLIC;

-- Agent access
GRANT USAGE ON AGENT WORKSHOP_DB.DEMO.DEMO_AGENT_CLOUD_COST TO ROLE PUBLIC;

-- Procedure access (for CostForecaster tool)
GRANT USAGE ON PROCEDURE WORKSHOP_DB.DEMO.FORECAST_COST(VARCHAR, VARCHAR, INT) TO ROLE PUBLIC;
GRANT USAGE ON PROCEDURE WORKSHOP_DB.DEMO.FORECAST_TOTAL_COST(INT) TO ROLE PUBLIC;

-- Model access (if using ML model directly)
-- GRANT USAGE ON MODEL WORKSHOP_DB.DEMO.COST_FORECASTING_MODEL TO ROLE PUBLIC;

-- Model Monitor access
-- GRANT USAGE ON MODEL MONITOR WORKSHOP_DB.DEMO.COST_MODEL_MONITOR TO ROLE PUBLIC;

-- Optional: Grant to specific role instead of PUBLIC
-- GRANT USAGE ON AGENT WORKSHOP_DB.DEMO.DEMO_AGENT TO ROLE DEMO_USER_ROLE;
